using System.Reflection;

namespace dotnet.openapi.generator;

internal static class Constants
{
    public const string Header = @"/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

";

    private static readonly Lazy<Version> _version = new(() => new Version(Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyFileVersionAttribute>()!.Version));
    public static Version Version => _version.Value;

    private static readonly Lazy<string> _productVersion = new(() => Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion);
    public static string ProductVersion => _productVersion.Value;
}